--- contacts-0.12/Makefile.am~	2009-07-14 16:00:54.000000000 +0200
+++ contacts-0.12/Makefile.am	2010-09-30 00:37:28.215261728 +0200
@@ -11,4 +11,4 @@
 MAINTAINERCLEANFILES = aclocal.m4 compile config.guess config.sub configure depcomp $(INTLTOOL_BUILT:=.in) install-sh ltmain.sh mkinstalldirs Makefile.in missing
 
 snapshot:
-        $(MAKE) dist distdir=$(PACKAGE)-snap`date +"%Y%m%d"`
+	$(MAKE) dist distdir=$(PACKAGE)-snap`date +"%Y%m%d"`
